[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "npm install && npm run build"
memory = 1024

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 